#Xroid

from datetime import datetime
from sys import version_info
from time import time
from dkbotz.Duration import TimeFormatter
from pyrogram import Client, filters
from xroid.humanbytes import humanbytes
from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup, Message
from configs import Config


@Client.on_message((filters.photo) & ~filters.channel)
async def help(client: Client, message: Message):
    if message.document:
       media = message.document
    if message.video:
       media = message.video
    if message.audio:
       media = message.audio
    if message.photo:
       media = message.photo

    text = ""

    text = "**🎢 Photo Details:**\n\n"
    text += f"__✏️ **Caption** : __ `{message.caption}`\n\n" if message.caption else ""
    text += f"🔰 __**Width** :__ `{media.width}`\n\n" if media.width else ""
    text += f"⭕ __** Height **:__ `{media.height}`\n\n" if media.height else ""
    text += f"📊 __** File Size** :__ `{humanbytes(media.file_size)}`\n\n" if media.file_size else ""
    text += f"**Generated By @{Config.BOT_USERNAME}**\n\n"

    await message.reply_text(text, quote=True)

